<<<<<<< HEAD
uuid: c8a7c39b-a386-4f6e-9ea7-d13f99405743
=======
>>>>>>> e5782c0467488c4ed9583877bea24221f86fafc6
langcode: fr
status: true
dependencies:
  config:
    - node.type.formation
id: node.formation.status
field_name: status
entity_type: node
bundle: formation
label: Publié
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
