<?php

/**
 * @file
 * Contains reseau_mod_up_pageprivee.module.
 */



/**
 * Implements hook_preprocess_html() for html templates.
 */
// function reseau_mod_up_pageprivee_preprocess_html(array &$variables) {
//   // Add META tag title + description for Basic Page node fields.
//   // This assumes the 'body' field is present and populated.
//   // Load the node entity from current route.
//   $node = \Drupal::routeMatch()->getParameter('node');
//   if ($node) {
//     // dsm($node);
//     // dsm($node->get('field_contenu_indexation')->getValue());
//     // Check if node type is basic page.
//     if ($node->getType() === 'page') {
//       if (!empty($node->get('field_contenu_indexation')->getValue())) {
//     if ($node->get('field_contenu_indexation')->getValue()[0]['value']=== '0') {
//       // dsm($variables['page']['#attached']['html_head']);

//       $variables['page']['#attached']['html_head'][] = [
//         [
//           '#tag' => 'meta',
//           '#attributes' => [
//             'name' => 'robots',
//             'content' => 'noindex, nofollow, noarchive, nosnippet, noodp, noydir, noimageindex, notranslate',
//           ],
//         ],
//         'robots',
//       ];

//     }
//     }
//     }
//   }
// }

function reseau_mod_up_pageprivee_page_attachments_alter(array &$attachments)
{
  /*ajoute css admin*/
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  $admin_theme_name = \Drupal::service('theme_handler')->getName($admin_theme);
  if ($admin_theme_name == 'Seven') {
    $attachments['#attached']['library'][] = 'reseau_mod_up_pageprivee/extra.privee';
  }

  $attachments['#attached']['library'][] = 'reseau_mod_up_pageprivee/reseau_mod_up_pageprivee';
}

/**
 * Implements hook_theme().
 */
function reseau_mod_up_pageprivee_theme()
{
  $theme['node__page__password_protected'] = [
    'base hook' => 'node',
  ];

  $theme['field__node__title__page_private_full'] = [
    'base hook' => 'field',
  ];

  $theme['field__node__title__page_private_password_protected'] = [
    'base hook' => 'field',
  ];

  return $theme;
}


/* 
Implements hook_theme_suggestions_HOOK_alter().
*/
function reseau_mod_up_pageprivee_theme_suggestions_field_alter(array &$suggestions, array $variables)
{

  $element = $variables['element'];
      if ($element['#field_name'] == 'title') {
        $node = \Drupal::routeMatch()->getParameter('node');
        if ($node instanceof \Drupal\node\NodeInterface) {
          if (($node->hasField("field_password")) && (!empty($node->get('field_password')->getValue()))) {
        dsm($node->get('field_password')->getValue());
        if ($node->get('field_password')[0]->get('is_protected')->getValue() == true) {
          dsm($node->get('field_password')[0]->get('is_protected')->getValue());
          $suggestions[] = 'field__node__title__page_private_' . $element['#view_mode'];
        }
       
      }
    }
  }
}
