<<<<<<< HEAD
uuid: fa8d4a2d-e848-4730-b812-52fa9d3e2baf
=======
>>>>>>> e5782c0467488c4ed9583877bea24221f86fafc6
langcode: fr
status: true
dependencies:
  config:
    - views.view.agenda
  module:
    - system
    - views
  theme:
    - reseau
id: views_block__agenda_block_3
theme: reseau
region: actualitesagenda
weight: 0
provider: null
plugin: 'views_block:agenda-block_3'
settings:
  id: 'views_block:agenda-block_3'
  label: ''
  label_display: '0'
  provider: views
  views_label: ''
  items_per_page: none
visibility:
  request_path:
    id: request_path
    negate: false
    pages: "/greta-guadeloupe\r\n/gip-daifi\r\n/cfapag\r\n/greta-st-martin-st-barth\r\n/capsbh"
